const LANGUAGE_STORAGE_KEY = 'guitar-chords-library-language';
const THEME_STORAGE_KEY = 'guitar-chords-library-theme';

const TRANSLATIONS = {
    en: {
        language: 'Language', libraryTitle: 'Guitar Chords Library', librarySubtitle: 'All the chords you need, at your fingertips',
        identifierTitle: 'Chord Identifier', identifierSubtitle: 'Click on the fretboard to select notes and find the chord',
        circleTitle: 'Circle of Fifths', circleSubtitle: 'Explore keys, modes, and chord relationships',
        chordLibrary: 'Chord Library', chordIdentifier: 'Chord Identifier', circleOfFifths: 'Circle of Fifths',
        all: 'All', pinned: 'Pinned', key: 'Key:', mode: 'Mode:', scaleNotes: 'Scale Notes', diatonicChords: 'Diatonic Chords', keyRelationships: 'Key Relationships',
        clearAll: 'Clear All', cancelPreview: 'Cancel Preview', selectedNotes: 'Selected Notes', identifiedChord: 'Identified Chord', noNotesSelected: 'No notes selected',
        instructions: 'How to use:', instruction1: 'Click on any fret position to add/remove a note', instruction2: 'Select at least 2 notes to identify a chord', instruction3: 'The chord is identified automatically as you select notes', instruction4: 'Click "Clear All" to start over',
        footer: 'Guitar Chords Library © 2026', disclaimer: 'This website was generated by AI. Information may contain errors or inaccuracies. Please verify independently before relying on any content.',
        shiftLeft: 'Shift chord left one fret', shiftRight: 'Shift chord right one fret', clickMore: 'Click for more shapes', noPinned: 'No pinned chords yet. Use the pin button on any chord diagram to add it here.',
        close: 'Close', menu: 'Menu', lightMode: 'Light mode', darkMode: 'Dark mode',
        major: 'Major', minor: 'Minor', diminished: 'Diminished', augmented: 'Augmented', unknown: 'Unknown', notes: 'Notes', selectTwo: 'Select at least 2 notes to identify a chord', selectDifferent: 'Select different notes (currently only one pitch class)', noMatch: "This combination doesn't exactly match a standard chord.", suggestions: 'Suggested chords (hover to preview, click to pin):', otherPossibilities: 'Other possibilities (hover to preview, click to pin):', notesMatch: 'notes match', missing: 'missing',
        relativeMinor: 'Relative Minor:', relativeMajor: 'Relative Major:', dominant: 'Dominant (V):', subdominant: 'Subdominant (IV):', parallel: 'Parallel:', keySignature: 'Key Signature:', chordShape: 'Chord Shape', shapeUnavailable: 'Shape unavailable'
    },
    'zh-Hant': {
        language: '語言', libraryTitle: '吉他和弦庫', librarySubtitle: '所有需要的和弦，隨手可得', identifierTitle: '和弦辨識器', identifierSubtitle: '點擊指板選取音符並找出和弦', circleTitle: '五度圈', circleSubtitle: '探索調性、調式與和弦關係', chordLibrary: '和弦庫', chordIdentifier: '和弦辨識器', circleOfFifths: '五度圈', all: '全部', pinned: '已釘選', key: '調性：', mode: '調式：', scaleNotes: '音階音符', diatonicChords: '自然和弦', keyRelationships: '調性關係', clearAll: '清除全部', cancelPreview: '取消預覽', selectedNotes: '已選音符', identifiedChord: '辨識的和弦', noNotesSelected: '尚未選取音符', instructions: '使用方式：', instruction1: '點擊任一琴格以加入或移除音符', instruction2: '至少選取兩個音符來辨識和弦', instruction3: '選取音符時會自動辨識和弦', instruction4: '點擊「清除全部」重新開始', footer: '吉他和弦庫 © 2026', disclaimer: '本網站由 AI 產生。資訊可能有錯誤或不準確之處，請在使用前自行查證。', shiftLeft: '將和弦向左移一格', shiftRight: '將和弦向右移一格', clickMore: '點擊查看更多按法', noPinned: '尚未釘選和弦。使用任一和弦圖上的圖釘按鈕即可加入。', close: '關閉', menu: '選單', lightMode: '淺色模式', darkMode: '深色模式', major: '大和弦', minor: '小和弦', diminished: '減和弦', augmented: '增和弦', unknown: '未知', notes: '音符', selectTwo: '至少選取兩個音符來辨識和弦', selectDifferent: '請選取不同音符（目前只有一個音高類別）', noMatch: '此組合並不完全符合標準和弦。', suggestions: '建議和弦（懸停預覽，點擊釘選）：', otherPossibilities: '其他可能性（懸停預覽，點擊釘選）：', notesMatch: '個音符符合', missing: '個缺少', relativeMinor: '關係小調：', relativeMajor: '關係大調：', dominant: '屬和弦 (V)：', subdominant: '下屬和弦 (IV)：', parallel: '同主調：', keySignature: '調號：', chordShape: '和弦指型', shapeUnavailable: '指型不可用'
    },
    'zh-Hans': {
        language: '语言', libraryTitle: '吉他和弦库', librarySubtitle: '所有需要的和弦，随手可得', identifierTitle: '和弦识别器', identifierSubtitle: '点击指板选择音符并找出和弦', circleTitle: '五度圈', circleSubtitle: '探索调性、调式与和弦关系', chordLibrary: '和弦库', chordIdentifier: '和弦识别器', circleOfFifths: '五度圈', all: '全部', pinned: '已置顶', key: '调性：', mode: '调式：', scaleNotes: '音阶音符', diatonicChords: '自然和弦', keyRelationships: '调性关系', clearAll: '清除全部', cancelPreview: '取消预览', selectedNotes: '已选音符', identifiedChord: '识别的和弦', noNotesSelected: '尚未选择音符', instructions: '使用方式：', instruction1: '点击任一琴格以添加或移除音符', instruction2: '至少选择两个音符来识别和弦', instruction3: '选择音符时会自动识别和弦', instruction4: '点击“清除全部”重新开始', footer: '吉他和弦库 © 2026', disclaimer: '本网站由 AI 生成。信息可能有错误或不准确之处，请在使用前自行核实。', shiftLeft: '将和弦向左移一格', shiftRight: '将和弦向右移一格', clickMore: '点击查看更多按法', noPinned: '尚未置顶和弦。使用任一和弦图上的图钉按钮即可添加。', close: '关闭', menu: '菜单', lightMode: '浅色模式', darkMode: '深色模式', major: '大和弦', minor: '小和弦', diminished: '减和弦', augmented: '增和弦', unknown: '未知', notes: '音符', selectTwo: '至少选择两个音符来识别和弦', selectDifferent: '请选择不同音符（当前只有一个音高类别）', noMatch: '此组合并不完全符合标准和弦。', suggestions: '建议和弦（悬停预览，点击置顶）：', otherPossibilities: '其他可能性（悬停预览，点击置顶）：', notesMatch: '个音符符合', missing: '个缺少', relativeMinor: '关系小调：', relativeMajor: '关系大调：', dominant: '属和弦 (V)：', subdominant: '下属和弦 (IV)：', parallel: '同主调：', keySignature: '调号：', chordShape: '和弦指型', shapeUnavailable: '指型不可用'
    }
};

Object.assign(TRANSLATIONS.en, {
    seventh: '7th', major7: 'Maj7', minor7: 'm7', dim: 'Dim', aug: 'Aug', sus2: 'Sus2', sus4: 'Sus4',
    ionian: 'Ionian', dorian: 'Dorian', phrygian: 'Phrygian', lydian: 'Lydian', mixolydian: 'Mixolydian', aeolian: 'Aeolian', locrian: 'Locrian', allShapes: 'All Shapes',
    zoomIn: 'Enlarge chord diagrams (1.5×)', zoomOut: 'Restore normal diagram size (1×)',
    songwriting: 'Songwriting', songwritingTitle: 'Songwriting', songwritingSubtitle: 'Write lyrics and place chords exactly where they belong', chordReference: 'Chord Reference', emptyChordReference: 'Chords you add to your lyrics will appear here.', noteReference: 'Note Reference', emptyNoteReference: 'Select a song key to see its scale notes.', songTitle: 'Untitled Song', addLine: 'Add line', exportJson: 'Export JSON', importJson: 'Import JSON', chord: 'Chord', addChord: 'Add chord', lyricPlaceholder: 'Write a lyric line...', lyricLine: 'Lyric line', removeLine: 'Remove line', removeChord: 'Remove chord', updateChord: 'Update chord', invalidSongFile: 'This JSON file is not a valid song.', chooseChord: 'Choose a chord', findChord: 'Find a chord', songKey: 'Key', relatedChords: 'Related Chords', otherRelatedChords: 'Other Related Chords', otherChords: 'Other Chords', bassNote: 'Bass note', bassHint: 'Optional - type a note to add the chord as a slash chord, e.g. C/G', bassInvalid: 'Not a note name (try C, F#, Bb)', chordLabelHint: 'Click to change, drag to move', noChordsFound: 'No chords found', songKeyHint: 'Select one or more keys', apply: 'Apply', chooseShape: 'Choose a chord shape', noteNotInKey: 'This note is not in the song key', confirmOverwriteSong: 'The editor already has content. Importing will replace it. Continue?', newSong: 'New Song', confirmNewSong: 'Start a new song? Current content will be cleared.', dropJsonHere: 'Drop JSON here', confirmTitle: 'Confirm', cancel: 'Cancel', confirm: 'Confirm'
});
Object.assign(TRANSLATIONS['zh-Hant'], {
    seventh: '屬七', major7: '大七', minor7: '小七', dim: '減', aug: '增', sus2: '掛二', sus4: '掛四',
    ionian: '伊奧尼亞', dorian: '多利安', phrygian: '弗里幾亞', lydian: '利底亞', mixolydian: '混合利底亞', aeolian: '愛奧尼亞', locrian: '洛克里亞', allShapes: '所有指型',
    zoomIn: '放大和弦圖（1.5×）', zoomOut: '回復和弦圖正常大小（1×）',
    songwriting: '歌曲創作', songwritingTitle: '歌曲創作', songwritingSubtitle: '撰寫歌詞並在正確位置加入和弦', chordReference: '和弦參考', emptyChordReference: '加入歌詞的和弦會顯示在這裡。', noteReference: '音符參考', emptyNoteReference: '請選擇歌曲調性以查看音階音符。', songTitle: '未命名歌曲', addLine: '新增行', exportJson: '匯出 JSON', importJson: '匯入 JSON', chord: '和弦', addChord: '加入和弦', lyricPlaceholder: '輸入一行歌詞...', lyricLine: '歌詞行', removeLine: '刪除行', removeChord: '刪除和弦', updateChord: '更新和弦', invalidSongFile: '這個 JSON 檔案不是有效的歌曲。', chooseChord: '選擇和弦', findChord: '尋找和弦', relatedChords: '相關和弦', otherRelatedChords: '其他相關和弦', otherChords: '其他和弦', bassNote: '低音音符', bassHint: '選填：輸入音符即可加入斜線和弦，例如 C/G', bassInvalid: '不是有效的音符名稱（例如 C、F#、Bb）', chordLabelHint: '點擊可變更，拖曳可移動', noChordsFound: '找不到和弦', songKeyHint: '請選擇一個或多個調性', apply: '套用', chooseShape: '選擇和弦指型', noteNotInKey: '此音符不在歌曲調性內', confirmOverwriteSong: '編輯器已有內容。匯入將覆蓋現有內容。是否繼續？', newSong: '新歌曲', confirmNewSong: '開始新歌曲？目前的內容將被清除。', dropJsonHere: '在此放置 JSON 檔案', confirmTitle: '確認', cancel: '取消', confirm: '確認'
});
Object.assign(TRANSLATIONS['zh-Hans'], {
    seventh: '属七', major7: '大七', minor7: '小七', dim: '减', aug: '增', sus2: '挂二', sus4: '挂四',
    ionian: '伊奥尼亚', dorian: '多利亚', phrygian: '弗里吉亚', lydian: '利底亚', mixolydian: '混合利底亚', aeolian: '爱奥尼亚', locrian: '洛克里亚', allShapes: '所有指型',
    zoomIn: '放大和弦图（1.5×）', zoomOut: '恢复和弦图正常大小（1×）',
    songwriting: '歌曲创作', songwritingTitle: '歌曲创作', songwritingSubtitle: '撰写歌词并在正确位置添加和弦', chordReference: '和弦参考', emptyChordReference: '添加到歌词的和弦会显示在这里。', noteReference: '音符参考', emptyNoteReference: '请选择歌曲调性以查看音阶音符。', songTitle: '未命名歌曲', addLine: '新增行', exportJson: '导出 JSON', importJson: '导入 JSON', chord: '和弦', addChord: '添加和弦', lyricPlaceholder: '输入一行歌词...', lyricLine: '歌词行', removeLine: '删除行', removeChord: '删除和弦', updateChord: '更新和弦', invalidSongFile: '这个 JSON 文件不是有效的歌曲。', chooseChord: '选择和弦', findChord: '查找和弦', relatedChords: '相关和弦', otherRelatedChords: '其他相关和弦', otherChords: '其他和弦', bassNote: '低音音符', bassHint: '选填：输入音符即可添加斜线和弦，例如 C/G', bassInvalid: '不是有效的音符名称（例如 C、F#、Bb）', chordLabelHint: '点击可更改，拖拽可移动', noChordsFound: '未找到和弦', songKeyHint: '请选择一个或多个调性', apply: '应用', chooseShape: '选择和弦指型', noteNotInKey: '此音符不在歌曲调性内', confirmOverwriteSong: '编辑器已有内容。导入将覆盖现有内容。是否继续？', newSong: '新歌曲', confirmNewSong: '开始新歌曲？当前内容将被清除。', dropJsonHere: '在此放置 JSON 文件', confirmTitle: '确认', cancel: '取消', confirm: '确认'
});

function getLanguage() {
    return localStorage.getItem(LANGUAGE_STORAGE_KEY) || 'en';
}

// Dark is the default palette; light mode only applies once the user switches to it.
function getTheme() {
    return localStorage.getItem(THEME_STORAGE_KEY) === 'light' ? 'light' : 'dark';
}

function applyTheme() {
    const theme = getTheme();
    document.documentElement.dataset.theme = theme;
    const button = document.querySelector('.theme-button');
    if (!button) return;
    // The button announces the theme it switches to, matching the icon shown by style.css.
    const label = t(theme === 'light' ? 'darkMode' : 'lightMode');
    button.title = label;
    button.setAttribute('aria-label', label);
}

function getTopControls() {
    const existing = document.querySelector('.top-controls');
    if (existing) return existing;
    const controls = document.createElement('div');
    controls.className = 'top-controls';
    document.body.appendChild(controls);
    return controls;
}

function t(key) {
    const language = getLanguage();
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS.en[key] || key;
}

function applyTranslations() {
    const language = getLanguage();
    document.documentElement.lang = language;
    document.querySelectorAll('[data-i18n]').forEach(element => {
        element.textContent = t(element.dataset.i18n);
    });
    document.querySelectorAll('[data-i18n-title]').forEach(element => {
        element.title = t(element.dataset.i18nTitle);
        element.setAttribute('aria-label', t(element.dataset.i18nTitle));
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(element => {
        element.placeholder = t(element.dataset.i18nPlaceholder);
        element.dataset.placeholder = t(element.dataset.i18nPlaceholder);
    });
    document.querySelectorAll('[data-drop-hint]').forEach(element => {
        element.dataset.dropHint = t('dropJsonHere');
    });
}

function createThemeToggle() {
    const button = document.createElement('button');
    button.className = 'theme-button';
    button.type = 'button';
    button.innerHTML = `
        <svg class="theme-icon icon-sun" viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <circle cx="12" cy="12" r="5"/>
            <line x1="12" y1="1" x2="12" y2="3"/>
            <line x1="12" y1="21" x2="12" y2="23"/>
            <line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/>
            <line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/>
            <line x1="1" y1="12" x2="3" y2="12"/>
            <line x1="21" y1="12" x2="23" y2="12"/>
            <line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/>
            <line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/>
        </svg>
        <svg class="theme-icon icon-moon" viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/>
        </svg>`;

    button.addEventListener('click', () => {
        localStorage.setItem(THEME_STORAGE_KEY, getTheme() === 'light' ? 'dark' : 'light');
        applyTheme();
    });
    getTopControls().appendChild(button);
}

function createLanguageSelector() {
    const button = document.createElement('button');
    button.className = 'language-button';
    button.type = 'button';
    button.setAttribute('aria-label', t('language'));
    button.setAttribute('data-i18n-title', 'language');
    button.innerHTML = `
        <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <circle cx="12" cy="12" r="10"/>
            <path d="M2 12h20"/>
            <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/>
        </svg>`;

    const modal = document.createElement('div');
    modal.className = 'language-modal';
    modal.hidden = true;
    modal.innerHTML = `
        <div class="language-modal-backdrop"></div>
        <div class="language-modal-dialog" role="dialog" aria-modal="true" aria-label="${t('language')}">
            <h2 class="language-modal-title" data-i18n="language">${t('language')}</h2>
            <div class="language-options">
                <button type="button" class="language-option" data-lang="en">English</button>
                <button type="button" class="language-option" data-lang="zh-Hant">繁體中文</button>
                <button type="button" class="language-option" data-lang="zh-Hans">简体中文</button>
            </div>
            <button type="button" class="language-modal-close" data-i18n="close">${t('close')}</button>
        </div>`;

    const options = modal.querySelectorAll('.language-option');
    const open = () => {
        options.forEach(option => option.classList.toggle('selected', option.dataset.lang === getLanguage()));
        modal.hidden = false;
    };
    const close = () => { modal.hidden = true; };

    button.addEventListener('click', open);
    modal.querySelector('.language-modal-backdrop').addEventListener('click', close);
    modal.querySelector('.language-modal-close').addEventListener('click', close);
    document.addEventListener('keydown', event => {
        if (event.key === 'Escape' && !modal.hidden) close();
    });
    options.forEach(option => option.addEventListener('click', () => {
        localStorage.setItem(LANGUAGE_STORAGE_KEY, option.dataset.lang);
        applyTranslations();
        applyTheme();
        document.dispatchEvent(new Event('languagechange'));
        close();
    }));

    getTopControls().appendChild(button);
    document.body.appendChild(modal);
}

function createMobileNav() {
    const nav = document.querySelector('.main-nav');
    if (!nav) return;

    const links = [...nav.querySelectorAll('.nav-link')].map(link => ({
        href: link.getAttribute('href'),
        label: link.textContent.trim(),
        i18nKey: link.dataset.i18n,
        active: link.classList.contains('active')
    }));

    const button = document.createElement('button');
    button.className = 'mobile-nav-button';
    button.type = 'button';
    button.setAttribute('aria-label', t('menu'));
    button.innerHTML = `
        <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true">
            <line x1="4" y1="6" x2="20" y2="6"/>
            <line x1="4" y1="12" x2="20" y2="12"/>
            <line x1="4" y1="18" x2="20" y2="18"/>
        </svg>`;

    const modal = document.createElement('div');
    modal.className = 'mobile-nav-modal';
    modal.hidden = true;
    modal.innerHTML = `
        <div class="mobile-nav-backdrop"></div>
        <div class="mobile-nav-dialog" role="dialog" aria-modal="true" aria-label="${t('menu')}">
            <h2 class="mobile-nav-title" data-i18n="menu">${t('menu')}</h2>
            <div class="mobile-nav-links">
                ${links.map(link => `<a class="mobile-nav-link${link.active ? ' active' : ''}" href="${link.href}"${link.i18nKey ? ` data-i18n="${link.i18nKey}"` : ''}>${link.label}</a>`).join('')}
            </div>
            <button type="button" class="mobile-nav-close" data-i18n="close">${t('close')}</button>
        </div>`;

    const open = () => { modal.hidden = false; };
    const close = () => { modal.hidden = true; };

    button.addEventListener('click', open);
    modal.querySelector('.mobile-nav-backdrop').addEventListener('click', close);
    modal.querySelector('.mobile-nav-close').addEventListener('click', close);
    document.addEventListener('keydown', event => {
        if (event.key === 'Escape' && !modal.hidden) close();
    });

    document.body.appendChild(button);
    document.body.appendChild(modal);
}

document.addEventListener('DOMContentLoaded', () => {
    applyTranslations();
    createThemeToggle();
    createLanguageSelector();
    createMobileNav();
    applyTheme();
});
